package glitched.adlips.application.user;

public enum UserErrorCode {
    VALIDATION_ERROR,
    AUTH_FAILED_GOOGLE,
    SIGNUP_REQUIRED,
    DUPLICATE_NICKNAME,
    ALREADY_REGISTERED,
    UNAUTHORIZED_ACCESS,
    USER_NOT_FOUND,
    PROFILE_NOT_FOUND,
    PRIVATE_PROFILE,
    INVALID_IMAGE_FILE,
    CANNOT_FOLLOW_SELF,
    ALREADY_FOLLOWING,
    FOLLOW_NOT_FOUND,
    INVALID_RELATION_TYPE
}
