package glitched.adlips.application.project;

public enum ProjectErrorCode {
    VALIDATION_ERROR,
    PROJECT_NOT_FOUND,
    TRACK_NOT_FOUND,
    INVALID_TRACK_VOLUME,
    PROJECT_ACCESS_DENIED,
    TRACK_EDIT_DENIED,
    TRACK_DELETE_DENIED,
    MEDIA_FILE_NOT_FOUND,
    MEDIA_FILE_ACCESS_DENIED,
    MEDIA_FILE_NOT_READY,
    INVALID_ALBUM_IMAGE,
    TRACK_HAS_PENDING_CONTRIBUTION,
    EXPORT_TARGET_NOT_FOUND
}
